-- National Weather Big Data Analytics Platform
-- Supabase Postgres Schema Setup

-- 1. Create reports table
CREATE TABLE IF NOT EXISTS public.reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source TEXT NOT NULL DEFAULT 'citizen', -- 'citizen', 'reddit', 'kaggle_seed', 'imd'
    text_content TEXT NOT NULL,
    event_type TEXT NOT NULL, -- 'Flood', 'Heatwave', 'Thunderstorm', 'Fog', 'DustStorm', 'StrongWind', 'Other'
    city TEXT NOT NULL,
    state TEXT NOT NULL,
    latitude FLOAT8 NOT NULL,
    longitude FLOAT8 NOT NULL,
    photo_url TEXT DEFAULT NULL,
    video_url TEXT DEFAULT NULL,
    posted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    verification_status TEXT NOT NULL DEFAULT 'pending', -- 'verified', 'pending', 'rejected'
    trust_score FLOAT8 NOT NULL DEFAULT 50.0,
    is_duplicate BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Indexes for performance & spatial location queries (Plain Lat/Lng Spatial Indexing)
CREATE INDEX IF NOT EXISTS idx_reports_event_type ON public.reports(event_type);
CREATE INDEX IF NOT EXISTS idx_reports_status ON public.reports(verification_status);
CREATE INDEX IF NOT EXISTS idx_reports_city ON public.reports(city);
CREATE INDEX IF NOT EXISTS idx_reports_state ON public.reports(state);
CREATE INDEX IF NOT EXISTS idx_reports_posted_at ON public.reports(posted_at DESC);
CREATE INDEX IF NOT EXISTS idx_reports_spatial ON public.reports(latitude, longitude);

-- 3. Enable Row Level Security (RLS)
ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;

-- Allow public read access to verified reports only
CREATE POLICY "Public users can view verified reports" 
ON public.reports 
FOR SELECT 
USING (verification_status = 'verified');

-- Allow service role full access (inserted/updated by backend)
CREATE POLICY "Service role full access on reports" 
ON public.reports 
FOR ALL 
TO service_role 
USING (true) 
WITH CHECK (true);

-- 4. Enable Supabase Realtime on reports table
ALTER PUBLICATION supabase_realtime ADD TABLE public.reports;

-- 5. Storage Bucket Setup (weather-media)
-- Execute this SQL in Supabase SQL Editor to create public storage bucket if needed
INSERT INTO storage.buckets (id, name, public) 
VALUES ('weather-media', 'weather-media', true)
ON CONFLICT (id) DO NOTHING;

-- Storage RLS Policies
CREATE POLICY "Public read access for weather media"
ON storage.objects FOR SELECT
USING (bucket_id = 'weather-media');

CREATE POLICY "Service role upload access for weather media"
ON storage.objects FOR INSERT
TO service_role
WITH CHECK (bucket_id = 'weather-media');
